# Use the correct Node.js 20 Alpine image tag
FROM node:20-alpine3.19 

# Set the working directory
WORKDIR /app

# Copy package.json
COPY package.json ./

# Install dependencies
RUN yarn install && yarn add global nodemon

# Copy other files
COPY tsconfig.json ./
COPY nodemon.json ./
COPY src ./src
COPY tsoa.json ./

# Expose the application's port
EXPOSE 3000

# Command to run the application
CMD ["yarn", "dev"]